glossary.md
=> docs: add glossary document

PracticalEmailManagement/README.md
=> docs: ✏️ add context to project readme

.github/pull_request_template.md, .github/workflows/practical_email_management.yml, .gitignore, PracticalEmailManagement/README.md, README.md, docs/technical_plans/0001-practical-email-management/practical-email-management.md, glossary.md, package.json
=> release: v0.1.0: project context

.github/pull_request_template.md, .github/workflows/practical_email_management.yml, .gitignore, PracticalEmailManagement/README.md, README.md, docs/technical_plans/0001-practical-email-management/practical-email-management.md, glossary.md, package.json
* Update README.md
* Update README.md
* style: fix formatting
* Update README.md
* feat: 🎸 add practical email management project folder (#3)
* feat: 🎸 add practical email management project folder
* chore: 🤖 add pull request template
* ci: 🎡 add github workflow
* docs: add glossary document (#6)
* chore: 🤖 add package info
* chore: 🤖 update .gitignore
* docs: ✏️ add technical plan document (#5)
* docs: ✏️ add technical plan document
* docs: ✏️ add risks
* docs: ✏️ add prerequisites
* docs: ✏️ add diagrams
* docs: ✏️ add feature
* docs: ✏️ add scenarios
* docs: ✏️ add gherkin to scenario
* docs: ✏️ add uat
* docs: add table of contents
* docs: clean up sentence
* docs: clarify
* docs: add to glossary
* docs: add to glossary
* docs: clarify gherkin
* docs: add glossary item and standardize …
=> release: v0.1.0: project context (#16)

.github/workflows/practical_email_management.yml, PracticalEmailManagement/.gitignore, PracticalEmailManagement/README.md, PracticalEmailManagement/build.sh, PracticalEmailManagement/package.json, PracticalEmailManagement/src/Code.js, PracticalEmailManagement/src/appsscript.json
=> ci: 🎡 add google clasp

.github/workflows/practical_email_management.yml
- Merge and confirm deployment
=> ci: 🎡 setup deployment

.github/workflows/practical_email_management.yml
- Merge and confirm deployment
=> ci: add script_id

.github/workflows/practical_email_management.yml
=> ci: add node v3

.github/workflows/practical_email_management.yml, package-lock.json
=> ci: 🎡 enable clasp push

.github/workflows/practical_email_management.yml, package-lock.json
=> ci: Feat/fix deployment on merge

.github/pull_request_template.md, .github/workflows/practical_email_management.yml
=> chore: clean up workflow and template

.github/pull_request_template.md, .github/workflows/practical_email_management.yml, PracticalEmailManagement/package.json, package.json
* Update README.md
* Update README.md
* style: fix formatting
* Update README.md
* feat: 🎸 add practical email management project folder (#3)
* feat: 🎸 add practical email management project folder
* chore: 🤖 add pull request template
* ci: 🎡 add github workflow
* docs: add glossary document (#6)
* chore: 🤖 add package info
* chore: 🤖 update .gitignore
* docs: ✏️ add technical plan document (#5)
* docs: ✏️ add technical plan document
* docs: ✏️ add risks
* docs: ✏️ add prerequisites
* docs: ✏️ add diagrams
* docs: ✏️ add feature
* docs: ✏️ add scenarios
* docs: ✏️ add gherkin to scenario
* docs: ✏️ add uat
* docs: add table of contents
* docs: clean up sentence
* docs: clarify
* docs: add to glossary
* docs: add to glossary
* docs: clarify gherkin
* docs: add glossary item and standardize …
=> release: v0.2.1 (#29)

UsefulScripts/git_clean_branches.sh
=> feat: 🎸 add better messaging

.github/workflows/practical_email_management.yml, PracticalEmailManagement/README.md, PracticalEmailManagement/package-lock.json, PracticalEmailManagement/package.json, PracticalEmailManagement/test/Code.test.js, UsefulScripts/README.md, UsefulScripts/git_clean_branches.sh, package.json
* Update README.md
* Update README.md
* style: fix formatting
* Update README.md
* feat: 🎸 add practical email management project folder (#3)
* feat: 🎸 add practical email management project folder
* chore: 🤖 add pull request template
* ci: 🎡 add github workflow
* docs: add glossary document (#6)
* chore: 🤖 add package info
* chore: 🤖 update .gitignore
* docs: ✏️ add technical plan document (#5)
* docs: ✏️ add technical plan document
* docs: ✏️ add risks
* docs: ✏️ add prerequisites
* docs: ✏️ add diagrams
* docs: ✏️ add feature
* docs: ✏️ add scenarios
* docs: ✏️ add gherkin to scenario
* docs: ✏️ add uat
* docs: add table of contents
* docs: clean up sentence
* docs: clarify
* docs: add to glossary
* docs: add to glossary
* docs: clarify gherkin
* docs: add glossary item and standardize …
=> release: v0.3.0 (#34)

PracticalEmailManagement/README.md
- Test on your own gmail account
=> docs: add email divert instructions (issue-10)

PracticalEmailManagement/README.md
=> docs: ✏️ add storage for gmail queries (issue-14)

.github/workflows/practical_email_management.yml, PracticalEmailManagement/README.md, PracticalEmailManagement/package-lock.json, PracticalEmailManagement/src/Code.js, PracticalEmailManagement/src/Configuration.js, PracticalEmailManagement/src/MailRecovery.js, PracticalEmailManagement/test/Code.test.js, PracticalEmailManagement/test/MailRecovery.test.js, package-lock.json
=> docs: add script setup instructions

package.json, scripts/git_latest_version_tag.sh, scripts/git_predict_next_version.sh, scripts/run_tests.sh, scripts/tests/git_latest_version_tag_test.sh, scripts/tests/git_predict_next_version_test.sh
=> feat: add scripts to determine the next version

package.json, scripts/start_release.sh, scripts/tests/mock_cmd.sh, scripts/tests/start_release_test.sh
=> feat: support starting a release

.github/workflows/git-flow.yml
=> Release v0.4.0 to main

package.json, scripts/check_release_version.sh, scripts/run_tests.sh, scripts/start_hotfix.sh, scripts/tests/check_release_version_test.sh, scripts/tests/start_hotfix_test.sh
- All tests pass
- Create a hotfix with the command
=> feat: 51 support starting a hotfix

.github/workflows/git-flow.yml
✅ Closes: 68
- Merge to develop.  Everything should work
=> ci: 🎡 add missing dependency to job

.github/workflows/git-flow.yml
✅ Closes: 68
- Workflow completes successfully
=> fix: 🐛 add semantic pre-release

scripts/git_latest_version_tag.sh, scripts/tests/git_latest_version_tag_test.sh
=> release v0.4.0 to develop ↣

tooling/README.md, tooling/scripts/check_release_version.sh, tooling/scripts/parse_file_list_for_projects.sh
- The UsefulScripts project should build and test
=> chore: 🤖 add some documentation and comments

package.json
=> release v0.5.0 to develop ↣

tooling/scripts/parse_file_list_for_projects.sh, tooling/scripts/start_hotfix.sh, tooling/scripts/start_release.sh
=> feat: add support for setting pr body

.github/dependabot.yml, tooling/scripts/parse_file_list_for_projects.sh, tooling/scripts/start_hotfix.sh, tooling/scripts/start_release.sh
=> release v0.5.0 to main

.github/workflows/git-flow.yml, package.json
=> release v0.6.0 to develop ↣

.github/workflows/git-flow.yml, projects/practical-email-management/.depends
- Workflow completes when merged to develop
=> ci: modify workflow to support main and develop branches

package.json, tooling/scripts/generate_matrix.sh
=> release v0.7.0 to develop ↣

.github/workflows/git-flow.yml, .github/workflows/practical_email_management.yml, projects/practical-email-management/package.json, projects/practical-email-management/scripts/run-unit-tests.sh, tooling/scripts/generate_matrix.sh, tooling/scripts/gh_trigger_workflow_dispatch.sh, tooling/scripts/tests/generate_matrix_test.sh
=> ci: add workflow action

.github/workflows/git-flow.yml, tooling/scripts/gh_trigger_workflow_dispatch.sh
=> ci: use the matrix os

.github/pull_request_template.md, .github/workflows/git-flow.yml, .gitignore, tooling/scripts/determine_skip_e2e.sh, tooling/scripts/generate_matrix.sh, tooling/scripts/tests/generate_matrix_test.sh
=> ci: 🎡 change the order of the deploy-check job

.github/workflows/git-flow.yml, tooling/scripts/determine_skip_cd.sh, tooling/scripts/determine_skip_e2e.sh
=> ci: simplify job dependencies

.github/pull_request_template.md, .github/workflows/git-flow.yml, .github/workflows/practical_email_management.yml, .gitignore, package-lock.json, package.json, projects/practical-email-management/scripts/run-unit-tests.sh, tooling/scripts/determine_skip_cd.sh, tooling/scripts/determine_skip_e2e.sh, tooling/scripts/generate_matrix.sh, tooling/scripts/gh_trigger_workflow_dispatch.sh, tooling/scripts/tests/generate_matrix_test.sh
=> release v0.8.0 to main

package.json
=> release v0.8.0 to develop ↣

projects/eod-messages/README.md, projects/eod-messages/package.json, projects/eod-messages/src/Code.js, projects/eod-messages/src/EndOfDaySummary.js, projects/eod-messages/src/OpenAi.js, tooling/scripts/git_latest_version_tag.sh, tooling/scripts/tests/git_latest_version_tag_test.sh
=> feat: add end of day summary code

package-lock.json, projects/eod-messages/src/EndOfDaySummary.js
=> feat: 🎸 prevent calling openai on empty data

projects/eod-messages/src/EndOfDaySummary.js
=> fix: use object keys

.depends
Recompile root if package.json or package-lock.json changes
=> Update .depends for root package.json and package-lock.json changes

tooling/scripts/git_predict_next_version.sh, tooling/scripts/tests/git_predict_next_version_test.sh
=> fix: predicting next version

.github/workflows/git-flow.yml, .gitignore
=> ci: update node version

docs/assets/system-design-template.graphml
Create a template diagram to be used for system design
=> docs: template design diagram (NO-TICKET)
